### ISSUE TITLE
Duda con ConTeXt

### ISSUE THREAD

**Issue by mitawasona** [ousia/context-critica#1]
Hola, buenos días, 

Me excedo un poco y le hago una pregunta sobre ConTeXt por si sabe la respuesta y quiere ayudarme.

Vengo de LaTeX y todavía estoy empezando con esto del ConTeXt y no controlo mucho, pero sí me he leido el Manual  y la Excursión y he consultado en el "jardín", pero no he obtenido respuesta para mi duda, a ver si usted me puede ayudar. 

Dice Martínez Sousa que el texto de un capítulo debe empezar siempre a la misma altura después de dejar un espacio de cortesía. Con \setuphead y la opción "after" consigo que empiece a una distancia constante desde el título, no desde el margen del papel como dice Sousa. Si todos los títulos tuviesen una longitud fija se conseguiría el efecto, pero si un título ocupa una línea y otro dos el texto subsiguiente empieza a distinta altura. ¿Alguna idea?

Le agradecería mucho si pudiera ayudarme.

Un saludo

**Comment by ousia** [comment]
Me temo que no sé cómo hacerlo. Creo que lo mejor es preguntarlo en la lista de ConTeXt.

Nunca me lo había planteado. Por cierto, ¿se puede hacer eso en LaTeX?

**Comment by mitawasona** [comment]
Seguro que se puede hacer tanto en LaTeX como en ConTeXt, el problema es cuánto de "tricky" sea la solución, tampoco en LaTeX sé cómo se hace.

Lo hubiese preguntado en la lista antes de molestarlo, pero mi inglés solo alcanza para la lectura, no sé escribirlo.

Muchas gracias por emplear parte de su tiempo en ayudarme.

**Comment by ousia** [comment]
Yo haré la pregunta.

El caso nunca se me había planteado (vamos, ni lo había pensado).

Con un comentario que se me viene a la cabeza (y que es posible que esté mal), se me ocurre una cuestión:
- En la práctica, la longitud de los títulos del mismo tipo (en este caso, de capítulo) tiene que ser homogénea. Eso no siempre se da. O no tiene por qué darse.

**Comment by mitawasona** [comment]
Muchas gracias por tomarse la molestia de preguntar.

No, los títulos no tienen por qué tener la misma longitud. De hecho el caso se me dio porque estoy maquetando "El Príncipe" de Maquiavelo y un capítulo se titula "De los principados mixtos" y otro "De que modo hay que gobernar las ciudades o principados que, antes de ser ocupados, se regían por sus propias leyes"

**Comment by mitawasona** [comment]
Me estaba volviendo loco, he mirado overlays, layers, diferentes layouts para la página de inicio de capítulo... y no conseguía nada. Al final lo he logrado con un método muy sencillo, con un frame:

 \define[2]\capitulo{\framed[frame=off,height=4cm,width=\textwidth, align={high}]{#2}} 

\setuphead[chapter][command={\capitulo}]

Y ya está.

Muchas gracias por haberte preocupado y tomado todas esas molestias.

**Comment by ousia** [comment]
Muchas gracias por la respuesta.

Perdona que no haya contestado antes, pero nadie respondió a [mi pregunta en la lista de ConTeXt](https://mailman.ntg.nl/pipermail/ntg-context/2016/084841.html).

Ahora responderé a mi propia pregunta, citándote a ti y a tu respuesta.

Por cierto, si defines una alineación, no es necesario marcar que el ancho del marco sea igual que el del texto (`width=\textwidth` parece que puede eliminarse sin problemas).
